database:
  # Database types: MySQL | SQLite
  name: SQLite
  # MySQL connection data
  host: localhost
  port: 3306
  dbname: server
  username: root
  password: ''
# Server Modes: MULTI_ARENA, LOBBY (Lobby for Bungee Arena), ARENA (Arena for Bungee Lobby)
servermode: MULTI_ARENA