author: TwightLightDev
name: LostSkyWars
version: 3.0.00
softdepend: [packetevents, Vault, Citizens, LostParties, LostBoxes, TwightLightCore, Guilds, EpicAchievements, DecentHolograms, WorldEdit ]

main: org.twightlight.skywars.SkyWars
commands:
  friend:
    aliases: [friends, f]
    description: ''
  funitems:
    aliases: [ funitem, customitems, customitem ]
    description: ''